### ISSUE TITLE
Import resources from VEST Registry

### ISSUE THREAD

**Issue by antool** [agroportal/agroportal_web_ui#39]
It would be great to have two lists 
1) resources in rdf format ;
2) others resources (those ones will be registered with metadata only)

**Comment by antool** [comment]
For the non-rdf resources, we can possibly create an owl file describing them with their metadata. It will be easier to register them in AgroPortal.

**Comment by jonquet** [comment]
@valeriapesce 
Can you guys actually prepare a script (containing REST post/patch calls) with your apikey and we will just execute it after verification/discussion on the lists above. 
@antool  can share the REST command examples to generate from the content of the VEST we will grab.

**Comment by valeriapesce** [comment]
Hi Clement,
I'm not sure I understand this... do you want us to prepare an export in some standard format or to call the AgroPortal write API and post each vocabulary? (The second option will take a lot of time)

Can you give us a little more details on either the format you want or the API usage, especially which values you expect for each parameter, if URI or string etc. 

I saw a couple of POST API calls that could be used, but:

1) If we have only metadata and not the ontology itself, should we just call the ontology POST API? But with that we would not be able to post additional metadata that you normally attach to a submission. Should we then call the submission POST API to add metadata? But can we do it if we don't have the ontology file to upload?

2) Could you give us a full example of a call to the POST API to register a metadata-only ontology?

Actually, **it would be easier for us to just register the vocabularies manually**, given that we don't have a full-time developer working on this.

I will send you the list of vocabularies we would like to register so that you can see if they're OK for the AgroPortal. And then we'll just manually add them once you have the new metadata-only registration form ready.

Thanks,

Valeria

**Comment by jonquet** [comment]
Hello, 
Let's focus on "real ontologies with content" for the moment here. Because we do have the problem potentially identified during the AgroHackathon that "metadata only ontologies" do not actually have a submission.

What I am talking about is a text file that will contain the curl command to fire on AgroPortal in order to import the content of the VEST registry at a certain date. You should not do that manually or we will not have any trace of this. The workflow I suggest is:
- Proposed list of KOS from VEST to include in AP
- Discussed and approuved list at date D
- The list is transformed into a text file containing the curl command to execute to upload each ontologies from the list 
- We run a script to load the list

Rather than working manually to upload the resources, you just write everything in a file (that we can reuse if needed (whereas manual actions cannot be reused))

The command will look like : 
To create an ontology:

```
curl    -X PUT
-H "Content-Type: application/json" 
-H "Authorization: apikey token=$APIKEY" 
-d '{ "acronym": "MO",
"name": "Movie Ontology",
"administeredBy": ["jonquet"]}' http://data.agroportal.lirmm.fr/ontologies/MO
```

To create a submission: 

```
curl    -X POST
-H "Content-Type: application/json" 
-H "Authorization: apikey token=$APIKEY"
-d '{   "contact": [{   "name": "Clément Jonquet",
"email": "jonquet@lirmm.fr"}],
"ontology": "http://data.agroportal.lirmm.fr/ontologies/MO",
"hasOntologyLanguage": "OWL",
"released": "2013-01-01T16:40:48-08:00",
"pullLocation":"http://www.movieontology.org/2010/01/movieontology.owl"}'
http://data.agroportal.lirmm.fr/ontologies/MO/submissions 
```

@antool do we need another call ?

**Comment by jonquet** [comment]
Currently reviewing the list of candidates sent out by Valeria. Move to GDoc:
https://docs.google.com/document/d/1ohoaH8lwR8CIe0B5L-jxXn9CA00TmoAB3kRn2HKKqM4/edit
and
https://docs.google.com/document/d/1oI7_miBi1P3bZOGcURAxaGyG_4-BpXLzZX3bKEUHJXs/edit

**Comment by jonquet** [comment]
There is now automatic pulling from the VEST/AgroPortal Map: http://vest.agrisemantics.org/
But the other way arround is done.

When a "resource" is uplaoded to the VEST, the user is sugegsted to upload it to AgroPortal if the resource exists in a format that we can parse.
