### ISSUE TITLE
Number of classes on Welcome page count SKOS concepts ?

### ISSUE THREAD

**Issue by jonquet** [agroportal/agroportal_web_ui#92]
I am enclain to say no. 
We just added Agrovoc on AgroPortal (600K concepts in skos) and the number did not changed.

**Comment by vemonet** [comment]
Class count is computed using OWLAPI.

The OWLAPI don't handle skos:Concept. The SKOS format feature in BioPortal is not as interesting as the OWL format. When parsing a skos ontology the OWLAPI put all skos:Concept as NamedIndividual
```xml
 <NamedIndividual rdf:about="http://opendata.inra.fr/anaeeThes/c2_1272">
        <rdf:type rdf:resource="http://www.w3.org/2004/02/skos/core#Concept"/>
 </NamedIndividual>
```

BioPortal compute the metrics using OWLAPI, so the skos:Concept are not counted

On the Portal the handling of SKOS is a hack where we use NamedIndividual as classes instead of the properly parsed owl:Class

The owlapi_wrapper don't do anything different for SKOS or OWL

Counting skos:Concept would imply big change in the owlapi_wrapper (where we would need to warn him that it is a SKOS ontology, and parse in an other way)


But skos:Concept are counted as individuals (we can see AGROVOC has 681570 individuals)

I think we have 2 possibilities :  
* Displaying also the number of individuals for every ontology
* Displaying the number of individuals instead of the number of the number of classes for SKOS ontologies

**Comment by vemonet** [comment]
http://stageportal.lirmm.fr/ontologies

Now showing individuals count for SKOS ontologies (instead of class count) in browse, because skos:Concepts are counted as individuals

@jonquet you can close it if it is good for you, it will be in production at the next update

**Comment by jonquet** [comment]
Great for the sorting on the /ontologies page. 
On the welcome page, yes, let's just write the number of instances under the number of classes. 
And add a '?' button that says 
"Metrics are computed by the OWL API. The number of classes and instances roughly represent the number of concepts in the portal respectively for OWL ontologies and SKOS vocabularies" 

When done we will make a pull request for NCBO  @mdorf  and @jvendetti

**Comment by vemonet** [comment]
I have added the ? details
I don't if it will be interesting for NCBO since they only have 2 skos ontologies, but I have done the pull request
